### ISSUE TITLE
encoding large floats doesn't work in any IE or Edge

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/superpack-js#21]
Float/double encoding relies on the output of `Number.prototype.toString` with radix `2`. In V8,

```
> 3.1e124.toString(2)
'101110111001010000100011110001100100010101111010110100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
```

In Edge,

```
> 3.1e124.toString(2)
"1011101110010100001000111100011001000101011110101101(e+413)"
```

**Comment by LewisJEllis** [comment]
> The precise algorithm is implementation-dependent, however the algorithm should be a generalization of that specified in 7.1.12.1.
> -- [20.3.1.6 Number.prototype.toString](http://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.tostring)

Nice.

The easy bandaid would obviously be to just have a special case to parse this alternate form, but I also recall during initial research into float/double encoding reading an implementation that didn't depend on `Number.prototype.toString`, but instead did more bit twiddling to come up with the exponent and mantissa. It probably would've been in some implementation of some related format, but I don't recall where specifically.

**Comment by michaelficarra** [comment]
Yeah, it wouldn't be too hard to come up with a mathematical derivation of those values. Pull requests welcome :wink:.
