### ISSUE TITLE
Finish LICENSE attribution.

### ISSUE THREAD

**Issue by sanscore** [shapesecurity/superpack-js#6]
https://github.com/shapesecurity/superpack-js/blob/master/LICENSE#L190

**Comment by michaelficarra** [comment]
This is just part of the Apache 2.0 license. See the lines above for context: https://github.com/shapesecurity/superpack-js/blob/68bfd3a3d1e5d3a63c4208c93166ca5cf528a093/LICENSE#L179-L184
